server:
    port: 8081

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "http://localhost:3000"
                        allowedMethods:
                            - GET
                            - POST
                            - DELETE
            kubernetes:
                reload:
                    enabled: false
                    url-expression: "uri+'/'"
                discovery:
                    enabled: false
                    locator:
                        enabled: false
                        url-expression: "http://'+serviceId+':'+getPort()"
                        lower-case-service-id: true
