
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#   create-envfile:
 
#     runs-on: ubuntu-latest
 
#     steps:
#     - name: create .env file
#       run: | 
#         echo ${{ secrets.SECRET_KEY }} > .env
#       shell: bash
#       uses: SpicyPizza/create-envfile@v1.3
#       with:
#         envkey_DEBUG: false
#         envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
#         directory: ./
#         file_name: .env

  build:
#     needs: create-envfile
    runs-on: ubuntu-latest
    steps: 
    -
      name: create .env file
      run: |
        touch .env
        echo SECRET_KEY=${{ SECRET_KEY }} >> .env
        cat .env
      env: 
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - 
      name: Checkout code
      uses: actions/checkout@v2
    - 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push to Docker Hub
      uses: docker/build-push-action@v3
      with: 
          context: .
          push: true
          tags: martijnbassa/kwetter:api-gateway
