name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: create .env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        directory: ../../../
        file_name: .env
        fail_on_empty: false

  build:
    needs: create-envfile
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Docker login
      uses: actions/login-action@v1
      with:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with: 
          context: .
          push: true
          tags: martijnbassa/kwetter:latest, martijnbassa/kwetter:${{ github.run.number }}
    
